Revert "veux: Use the fragment for QTI vibrator HAL"
fatal error: 'audio_hw.h' file not found

This reverts commit 76451d81874a5e034b539da9dd3590bb5787ed64.